/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSolveMathRouteImport } from './routes/api/solve-math'
import { Route as ApiMathChatRouteImport } from './routes/api/math-chat'
import { Route as ApiImproveEssayRouteImport } from './routes/api/improve-essay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolveMathRoute = ApiSolveMathRouteImport.update({
  id: '/api/solve-math',
  path: '/api/solve-math',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMathChatRoute = ApiMathChatRouteImport.update({
  id: '/api/math-chat',
  path: '/api/math-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImproveEssayRoute = ApiImproveEssayRouteImport.update({
  id: '/api/improve-essay',
  path: '/api/improve-essay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/improve-essay': typeof ApiImproveEssayRoute
  '/api/math-chat': typeof ApiMathChatRoute
  '/api/solve-math': typeof ApiSolveMathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/improve-essay': typeof ApiImproveEssayRoute
  '/api/math-chat': typeof ApiMathChatRoute
  '/api/solve-math': typeof ApiSolveMathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/improve-essay': typeof ApiImproveEssayRoute
  '/api/math-chat': typeof ApiMathChatRoute
  '/api/solve-math': typeof ApiSolveMathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/improve-essay' | '/api/math-chat' | '/api/solve-math'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/improve-essay' | '/api/math-chat' | '/api/solve-math'
  id:
    | '__root__'
    | '/'
    | '/api/improve-essay'
    | '/api/math-chat'
    | '/api/solve-math'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiImproveEssayRoute: typeof ApiImproveEssayRoute
  ApiMathChatRoute: typeof ApiMathChatRoute
  ApiSolveMathRoute: typeof ApiSolveMathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/solve-math': {
      id: '/api/solve-math'
      path: '/api/solve-math'
      fullPath: '/api/solve-math'
      preLoaderRoute: typeof ApiSolveMathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/math-chat': {
      id: '/api/math-chat'
      path: '/api/math-chat'
      fullPath: '/api/math-chat'
      preLoaderRoute: typeof ApiMathChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/improve-essay': {
      id: '/api/improve-essay'
      path: '/api/improve-essay'
      fullPath: '/api/improve-essay'
      preLoaderRoute: typeof ApiImproveEssayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiImproveEssayRoute: ApiImproveEssayRoute,
  ApiMathChatRoute: ApiMathChatRoute,
  ApiSolveMathRoute: ApiSolveMathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
