/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSolveMathRouteImport } from './routes/api/public/solve-math'
import { Route as ApiPublicPracticeGenerateRouteImport } from './routes/api/public/practice-generate'
import { Route as ApiPublicMathChatRouteImport } from './routes/api/public/math-chat'
import { Route as ApiPublicImproveEssayRouteImport } from './routes/api/public/improve-essay'
import { Route as ApiPublicEssayGenerateRouteImport } from './routes/api/public/essay-generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSolveMathRoute = ApiPublicSolveMathRouteImport.update({
  id: '/api/public/solve-math',
  path: '/api/public/solve-math',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPracticeGenerateRoute =
  ApiPublicPracticeGenerateRouteImport.update({
    id: '/api/public/practice-generate',
    path: '/api/public/practice-generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMathChatRoute = ApiPublicMathChatRouteImport.update({
  id: '/api/public/math-chat',
  path: '/api/public/math-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImproveEssayRoute = ApiPublicImproveEssayRouteImport.update({
  id: '/api/public/improve-essay',
  path: '/api/public/improve-essay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEssayGenerateRoute = ApiPublicEssayGenerateRouteImport.update({
  id: '/api/public/essay-generate',
  path: '/api/public/essay-generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/essay-generate': typeof ApiPublicEssayGenerateRoute
  '/api/public/improve-essay': typeof ApiPublicImproveEssayRoute
  '/api/public/math-chat': typeof ApiPublicMathChatRoute
  '/api/public/practice-generate': typeof ApiPublicPracticeGenerateRoute
  '/api/public/solve-math': typeof ApiPublicSolveMathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/essay-generate': typeof ApiPublicEssayGenerateRoute
  '/api/public/improve-essay': typeof ApiPublicImproveEssayRoute
  '/api/public/math-chat': typeof ApiPublicMathChatRoute
  '/api/public/practice-generate': typeof ApiPublicPracticeGenerateRoute
  '/api/public/solve-math': typeof ApiPublicSolveMathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/essay-generate': typeof ApiPublicEssayGenerateRoute
  '/api/public/improve-essay': typeof ApiPublicImproveEssayRoute
  '/api/public/math-chat': typeof ApiPublicMathChatRoute
  '/api/public/practice-generate': typeof ApiPublicPracticeGenerateRoute
  '/api/public/solve-math': typeof ApiPublicSolveMathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/essay-generate'
    | '/api/public/improve-essay'
    | '/api/public/math-chat'
    | '/api/public/practice-generate'
    | '/api/public/solve-math'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/essay-generate'
    | '/api/public/improve-essay'
    | '/api/public/math-chat'
    | '/api/public/practice-generate'
    | '/api/public/solve-math'
  id:
    | '__root__'
    | '/'
    | '/api/public/essay-generate'
    | '/api/public/improve-essay'
    | '/api/public/math-chat'
    | '/api/public/practice-generate'
    | '/api/public/solve-math'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicEssayGenerateRoute: typeof ApiPublicEssayGenerateRoute
  ApiPublicImproveEssayRoute: typeof ApiPublicImproveEssayRoute
  ApiPublicMathChatRoute: typeof ApiPublicMathChatRoute
  ApiPublicPracticeGenerateRoute: typeof ApiPublicPracticeGenerateRoute
  ApiPublicSolveMathRoute: typeof ApiPublicSolveMathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/solve-math': {
      id: '/api/public/solve-math'
      path: '/api/public/solve-math'
      fullPath: '/api/public/solve-math'
      preLoaderRoute: typeof ApiPublicSolveMathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/practice-generate': {
      id: '/api/public/practice-generate'
      path: '/api/public/practice-generate'
      fullPath: '/api/public/practice-generate'
      preLoaderRoute: typeof ApiPublicPracticeGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/math-chat': {
      id: '/api/public/math-chat'
      path: '/api/public/math-chat'
      fullPath: '/api/public/math-chat'
      preLoaderRoute: typeof ApiPublicMathChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/improve-essay': {
      id: '/api/public/improve-essay'
      path: '/api/public/improve-essay'
      fullPath: '/api/public/improve-essay'
      preLoaderRoute: typeof ApiPublicImproveEssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/essay-generate': {
      id: '/api/public/essay-generate'
      path: '/api/public/essay-generate'
      fullPath: '/api/public/essay-generate'
      preLoaderRoute: typeof ApiPublicEssayGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicEssayGenerateRoute: ApiPublicEssayGenerateRoute,
  ApiPublicImproveEssayRoute: ApiPublicImproveEssayRoute,
  ApiPublicMathChatRoute: ApiPublicMathChatRoute,
  ApiPublicPracticeGenerateRoute: ApiPublicPracticeGenerateRoute,
  ApiPublicSolveMathRoute: ApiPublicSolveMathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
